# docker-compose.yml
# Die 'version' ist veraltet und kann entfernt werden.

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
      - ./scripts:/scripts
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - mongo

  # Der Celery-Worker, der jetzt auch den Zeitplaner (Beat) ausführt
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    # KORREKTUR: Das '-B' Flag startet den integrierten Scheduler
    command: celery -A app.worker.celery_app worker -B --loglevel=info
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - redis
      - mongo

  # Die MongoDB-Datenbank
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env

  # Der Redis-Server für Celery
  redis:
    image: redis:alpine

volumes:
  mongo-data: